create database Academia;
use Academia;

CREATE TABLE ALUNO (
	MATRICULA INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(200) NOT NULL,
    CPF VARCHAR (14) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    SENHA VARCHAR (255) NOT NULL
);

INSERT ALUNO (NOME, CPF, EMAIL, SENHA)
VALUES ('Giuseppi', '123.456.789-08', 'teste@exemplo.com', 'admin');

CREATE TABLE ADM (
	ID_ADM INT PRIMARY KEY AUTO_INCREMENT,
    USUARIO VARCHAR (50) NOT NULL,
    SENHA VARCHAR (255) NOT NULL
);

INSERT ADM (USUARIO, SENHA)
VALUES ('Emoroyda', 'admin');

CREATE TABLE PROFESSOR (
	MATRICULA_PF INT PRIMARY KEY AUTO_INCREMENT,
    NOME_PF VARCHAR(200) NOT NULL,
    CPF_PF VARCHAR (11) NOT NULL,
    EMAIL_PF VARCHAR(255) NOT NULL,
    SENHA_PF VARCHAR (255) NOT NULL
);

CREATE TABLE AULAS (
	ID_TREINO INT PRIMARY KEY AUTO_INCREMENT,
    DATA_TREINO VARCHAR (100) NOT NULL,
    TREINOS ENUM("Peito", "Biceps", "Triceps", "Costas", "Perna", "Membros Superiores") NOT NULL,
    REPETICOES VARCHAR (20)
);

